version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'next'
        update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-major'
      - dependency-name: 'eslint-config-next'
        update-types:
          - 'version-update:semver-major'
    groups:
      npm-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - 'eslint*'
          - '@eslint/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - '*'
